# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-15 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171015_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='blogtext',
        ),
    ]
