# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-15 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171015_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='published_date',
        ),
    ]
