# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171015_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='Images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
