# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
