# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20171015_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='Images',
            new_name='images',
        ),
    ]
