# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20171016_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='images',
            field=models.ImageField(blank=True, upload_to='blog/img'),
        ),
    ]
